### ISSUE TITLE
.lock files left behind in PERL_INLINE_DIRECTORY

### ISSUE THREAD

**Issue by anthonybakermpls** [daoswald/Inline-CPP#29]
After a perl script builds inline CPP, a .lock file is left over in the PERL_INLINE_DIRECTORY under the username of the running user. This prevents subsequent runs by other users who share the PERL_INLINE_DIRECTORY and cannot delete the lock file left over. We are seeing this on Red hat linux with perl version 5.20.2 and inline:CPP version 0.71

**Comment by daoswald** [comment]
This is curious.  The only ".lock" file created by the Inline::CPP distribution is created in Makefile.PL.  It's unconditionally closed on line 222 of that file, and unlinked on line 225.  But this wouldn't be doing anything in PERL_INLINE_DIRECTORY.

While there is some locking going on in Inline/CPP.pm, that file is a typemap, and doesn't have a ".lock" extension.

I believe the problem you are seeing is coming from Inline (most likely), or Inline::C, both of which Inline::CPP inherits from.  I'm going to try to see if I can get confirmation of that suspicion from Inline/Inline::C maintainers before I close this though.

**Comment by mohawk2** [comment]
I implemented the locking in Inline, and I believe @daoswald is correct.

**Comment by anthonybakermpls** [comment]
But does it make sense that this problem goes away when I remove the locking code for the typemap file in /lib/Inline/CPP.pm ?

**Comment by daoswald** [comment]
I suggest opening an issue in the Inline repo, since the .lock file is generated by Inline.  If Inline determines that Inline::CPP is doing something wrong (which I don't think it is), then a new issue can be opened here.  Meanwhile I'll close here; I don't see anything happening in Inline::CPP that should be to blame.
