### ISSUE TITLE
Failure To Separate 'g++' and '-fno-strict-aliasing', Due To ExtUtils::CppGuess v0.10 Release?

### ISSUE THREAD

**Issue by wbraswell** [daoswald/Inline-CPP#34]
This is a critical bug, it is causing full RPerl test failure.

Since my tests were passing yesterday but are not today, and the only obviously-related package with a new release on CPAN since then is ExtUtils::CppGuess, I'm believe that may be the culprit.

https://travis-ci.org/wbraswell/rperl/jobs/79630017#L1926-L1927

\# g++-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -xc++ -c  -I"/home/travis/build/wbraswell/rperl/t" -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DNO_XSLOCKS -O2   -DVERSION=\"0.00\" -DXS_VERSION=\"0.00\" -fPIC "-I/home/travis/perl5/perlbrew/perls/5.18/lib/5.18.2/x86_64-linux/CORE"   eval_7_4971.c

\# /bin/sh: 1: g++-fno-strict-aliasing: not found

**Comment by daoswald** [comment]
I may need to revert the PR submitted by bulk88, which is unfortunate.
I'll look at it more closely within the next 24hrs.

On Thu, Sep 10, 2015 at 4:34 AM, William N. Braswell, Jr. <
notifications@github.com> wrote:

> This is a critical bug, it is causing full RPerl test failure.
>
> Since my tests were passing yesterday but are not today, and the only
> obviously-related package with a new release on CPAN since then is
> ExtUtils::CppGuess, I'm believe that may be the culprit.
>
> https://travis-ci.org/wbraswell/rperl/jobs/79630017#L1926-L1927
> g++-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include
> -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -xc++ -c
> -I"/home/travis/build/wbraswell/rperl/t" -fno-strict-aliasing -pipe
> -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE
> -D_FILE_OFFSET_BITS=64 -DNO_XSLOCKS -O2 -DVERSION=\"0.00\"
> -DXS_VERSION=\"0.00\" -fPIC
> "-I/home/travis/perl5/perlbrew/perls/5.18/lib/5.18.2/x86_64-linux/CORE"
> eval_7_4971.c /bin/sh: 1: g++-fno-strict-aliasing: not found
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daoswald/Inline-CPP/issues/34>.
>



-- 

David Oswald
daoswald@gmail.com

**Comment by bulk88** [comment]
in _get_cflags

 my $cflags = $self->_config->{ccflags};

needs to be

 my $cflags = ' ' . $self->_config->{ccflags};

I just noticed in _guess_win32 and _guess_unix , the cflags literal strings that used to be the only thing making up the final cflags passed to EUMM,  those literal strings all begin with a space, but Config ccflags isnt going to start with a space.

**Comment by daoswald** [comment]
Commit bb289ce now requires ExtUtils::CppGuess v0.11, which in turn resolves the issue in the way described by bulk88, above.  This is reflected in Inline::CPP v0.74, being pushed out to CPAN now.

**Comment by wbraswell** [comment]
It worked!
https://travis-ci.org/wbraswell/rperl/builds/79762728
