### ISSUE TITLE
"Ed J" Is Disruptive Of Peaceful Development Process

### ISSUE THREAD

**Issue by wbraswell** [daoswald/Inline-CPP#35]
Hello Everyone,

Ever since I started interacting with the Inline development team a few years ago, I have received nothing but a constant stream of negative comments and sarcastic harassment from "Ed J" aka @mohawk2 .  As far as I can tell, I have done nothing to warrant this treatment, and it has already been dealt with at least once in private by Inline founder @ingydotnet when I publicly retaliated against being mistreated.

At this point, I am unable to even talk to Inline::CPP team lead @daoswald about valid technical issues without being immediately targeted by "Ed J".  His long-time use of online anonymity, an openly accepted practice in the Perl community, seems to support this anti-social behavior.

My best guess is "Ed J" dislikes my use of Inline to make Perl run faster via RPerl, because this will likely obviate the need for his own PDL software project.  I am sorry this is the case, but I can't be expected to accept this kind of abuse or quit working on RPerl just because he has his feelings hurt.  RPerl is a serious software project and deserves at least a modicum of respect.

I am a strong, decade-long supporter of the Inline project, and I have non-trivial code present in the public distributions of both Inline::CPP and Inline::Filters.  It is neither acceptable nor appropriate for the Inline team leaders to passively condone this situation by continuing to allow it to go unaddressed any longer.

Earlier today, I voluntarily departed from the #inline channel on irc.perl.org due to the by-now-not-abnormal behavior of "Ed J".  For the time being, I will interact with the Inline team via Github, in hopes this issue can be resolved and all parties can continue working on Inline in peace.

Thanks,
~ Will

**Comment by mohawk2** [comment]
I asked Mr Braswell to try to have a quick look into why the latest issue he is complaining about happened. This is the response.

**Comment by wbraswell** [comment]
False.
"Ed J" made a sarcastic comment implying I was lazy because I asked for help with the double-build bug.

**Comment by wbraswell** [comment]
Furthermore, I have just been informed "Ed J" has been privately reprimanded on multiple occasions by senior members of the Perl community, but has chosen to ignore it.  The soft-handed nature of the Perl community does little to prevent this ongoing behavior.  I, for one, will no longer tolerate it.

**Comment by wbraswell** [comment]
Yet another 3rd-party appraisal of the long-term anti-social behavior:

"...the guy has serious problems. Confirmed."

http://irclog.perlgeek.de/perl11/2015-09-14

**Comment by mohawk2** [comment]
The guy who claimed I have "serious problems" said your ticket (this one) is silly. Want to have a think about that?

**Comment by shadowcat-mst** [comment]
@mohawk2

That's because reini's convinced nobody ever actions problems like this.

The PDL community found you a disruptive influence.

Your recent work on MakeMaker has introduced more bugs than features and you refuse to take responsibility for the problems, instead blaming the criticism on other people's attitudes rather than the shoddiness of your work.

You've nearly been removed from Inline development at least once already for your behaviour.

Want to have a think about *that* ?

**Comment by wbraswell** [comment]
@daoswald @ingydotnet 
I hereby officially request that some sanction be applied to indicate the Inline project does not consider such behavior acceptable.

**Comment by mohawk2** [comment]
Reini's wrong, it's not quite "nobody": http://irclog.perlgeek.de/mojo/2015-09-13#i_11209422 http://code.activestate.com/lists/perl5-porters/221936/

**Comment by shadowcat-mst** [comment]
Please let's not drag sri's personal vendetta against me into this issue; his completely ignoring the mojo code of conduct has caused enough damage to the mojo project and community without you making it worse.

**Comment by wbraswell** [comment]
As stated by @shadowcat-mst , this Github issue is related solely to misconduct by "Ed J", other concerns should be discussed elsewhere.

**Comment by daoswald** [comment]
This issue tracker is strictly for use in reporting and tracking technical issues with the Inline::CPP code base. Social issues are beyond the scope of this project. As the owner of this repo I reserve the right to remove contributors for any reason, and to close issues for any reason, including for not being relevant to the technical, code-related charter of the issue tracker.  I am especially sensitive to having my time intruded upon by disputes and attacks.  The only social policy for the Inline::CPP repository is that it is not a social repository. Code contributions and bug reports are welcome.  I am closing this issue and locking it from further discussion.  If this repository or project no longer serve an individual's needs, forking is always an option.

**Comment by daoswald** [comment]
The official collaborator list for Inline::CPP now consists of daoswald and ingydotnet.  Others are welcome and encouraged to continue to participate on technical issues through Issues and Pull Requests.
