### ISSUE TITLE
undefined symbol: _ZNSs4_Rep20_S_empty_rep_storageE

### ISSUE THREAD

**Issue by wbraswell** [daoswald/Inline-CPP#37]
Somebody (or something) has already created a Github gist containing my error:

https://gist.github.com/mpan-pl/5e850a276298ffbfaa12

I am using Xubuntu v14.04 with the stock Perl v5.18.

I have ExtUtils::MakeMaker v7.16 and g++ v4.8 installed system-wide, along with libstdc++6-dev and other needed packages, and I am attempting to use local::lib and cpanm to install Inline::CPP as I have always done.  This is the first time I've ever seen this problem, it is unique and I can't figure out how to fix it!

cpanm is attempting to install ExtUtils::CppGuess v0.11 as a dependency of Inline::CPP v0.74, which is where the error occurs.

Everything I can find on Google suggests this is a mismatch between something compiled with an old version of g++ verses a new version of g++, but in this case I don't know what is the "old compiled thing" and what is the "new compiled thing", much less how to fix the mismatch.  Please help!

**Comment by daoswald** [comment]
Closing this issue as it falls under the same category of Issue #38, and will benefit from the fix proposed therein.
