### ISSUE TITLE
Repo modernisation

### ISSUE THREAD

**Issue by mohawk2** [daoswald/Inline-CPP#41]
@daoswald Are you open to enabling Travis CI for this repo? If so, could you switch it on? With that done, I'll set up a `.travis.yml`.

Also, are you open to me moving the author tests out of `t` to `xt`? I'll make an author-test build for Travis.

Finally, would you like the build results to report to `#inline`? Also, if you want to, could you set up the IRC "service" on here so it also reports commits there?

**Comment by wbraswell** [comment]
I vote +1 on all 3 suggestions.

**Comment by mohawk2** [comment]
Huh, I'd forgotten I didn't have permissions on this repo (or co-maint on CPAN).

Another issue is the `Makefile.PL` is needlessly complex in its `Inline/CPP/Config.pm` handling, with locking, and reading, and truncating, and so on. This could be avoided by renaming that file to the same with `.in` or similar on the end, and reading / substituting from that into the actual `.pm` which could then be in `.gitignore`. This would avoid the pointless diffs that result from e.g. me building on my Ubuntu machine (which changes the `$compiler`). It could even be simplified further by using the `.PL` system built in to EUMM.

**Comment by daoswald** [comment]
I've added you (mohawk2) as a contributor on the repo. Yes, definitely open
to the three suggestions.

**Comment by mohawk2** [comment]
@daoswald Great, I will have a go soon. If you're in favour of enabling Travis and IRC, could you do that?

**Comment by mohawk2** [comment]
@daoswald See PR. I have not merged it since I'd prefer you to feel comfortable with it, and raise any issues beforehand, so I'll leave it to you to merge after any changes you feel necessary.
