### ISSUE TITLE
undefined value warning with use Inline 'info';

### ISSUE THREAD

**Issue by jimav** [daoswald/Inline-CPP#45]
use Inline 'info';
...causes this warning to appear:
**Can't use an undefined value as an ARRAY reference at .../Inline/C.pm line 315**

Using Inline::CPP VERSION 0.75 (the latest in cpan as of today)
and perl v5.26.2

reportbug data will be attached.

```
#!/usr/bin/perl
use strict; use warnings;
#use Inline 'reportbug';
use Inline 'info'; # **causes internal warning**
use Inline CPP => 'void foo() { printf("Hello\n"); }'
;
foo;
```
[Inline.REPORTBUG.tar.gz](https://github.com/daoswald/Inline-CPP/files/2990142/Inline.REPORTBUG.tar.gz)

**Comment by mohawk2** [comment]
Thanks for the report! This was due to Inline::CPP and Inline::C having different data structures internally, which is now (on `master`) not the case.
