### ISSUE TITLE
Parser bug caused enum name to be "undef" (patch attached)

### ISSUE THREAD

**Issue by jimav** [daoswald/Inline-CPP#47]
[patch2.txt](https://github.com/daoswald/Inline-CPP/files/2994971/patch2.txt)
Hi,
There's another glitch in the C++ parser because of the incompatible change to %item keys in Parse::RecDescent v1.89.  It is in the "enum" production, where $item{IDENTIFIER} should be $item{'IDENTIFIER(?)'}.  The result is that enum names are undef in the resulting $parser->{data} structure.

I discovered this while (ab)using your very nice C++ parser for my own purposes (to auto-generate code to convert class/structs data into Perl hashes).

Anyway, attached is a patch [updated].

Rather than introduce another variable like $class_part which is accessed via vary long package:: prefix, I replaced those special variables with a general "fixkey" function which strips any quantifier off of it's argument (or not).  This avoids having to hard-code the specific quantifier, e.g. "(?)" or "(s)" etc., in those variables.   The function is local in the parser, so can be called without a package::prefix.

P.S. IMO it would be fine at this point just require Parse::RecDescent v1.89 or later and get rid of that stuff altogether.   I don't know how to get cpanm to re-run the tests using my patched code, so I didn't run them (sorry). 

Best wishes,
-Jim Avera

**Comment by daoswald** [comment]
Thanks for all the investigation and work. I'll try to get some updates
published this weekend.

**Comment by mohawk2** [comment]
Thanks, merged!
