### ISSUE TITLE
Are C++ objects released when Perl references no longer exist ?

### ISSUE THREAD

**Issue by ibrierley** [daoswald/Inline-CPP#60]
Hi, I'm just having a play with Inline::CPP, thanks for all of the work.

One thing I'm a bit unsure of from the docs, lets say I have a C++ class or struct, and created a reference to it in Perl...eg

my $obj = new SomeClass;
or a struct, eg
my $struct = Inline::Struct::State->new;

and latest $obj or $struct go out of scope or are undefed and no references exist, are the C++ classes/structs released as well, or should I be doing something manually there ?

Just can't tell if some of my code is a memory leak waiting to happen :D.

**Comment by mohawk2** [comment]
I suspect it would indeed leak, and you'd need some `DESTROY` method to free the C(++) data.

**Comment by ibrierley** [comment]
Thanks, I will take a look at doing this!

**Comment by rurban** [comment]
I am not sure, but this looks suspicious. I'm pretty sure you dont need manual DESTROY hooks for your classes. The C++ destructors should be called by the objects going out of scope.

**Comment by mohawk2** [comment]
It would be easy to check; make a trivial C++ object with a destructor that prints a message, wrap in a Perl object with a `DESTROY` method that does similar, then have a Perl loop that runs 10 times, each one creating a Perl object that goes out of scope, and examine the output.

**Comment by ibrierley** [comment]
I just wanted to confirm that the destructor for the C++ object does get called each time after Perls DESTROY is called.

Many thanks for the help.
